FROM node:11 as compiled_angular
WORKDIR /app
COPY package*.json ./ 
RUN npm install
RUN npm install -g @angular/cli
COPY . .
RUN npm run ng build -- --prod --output-path=dist

FROM nginx
COPY nginx.conf /etc/nginx/
COPY --from=compiled_angular /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]



